#数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tumo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

#  配置基础路径
  mvc:
    servlet:
      path: /hms

#mybatis配置
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: com.ms.hms.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081

